# Generated by Django 4.1.5 on 2023-04-02 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0011_threadmodel_messagemodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='messagemodel',
            old_name='reciver_user',
            new_name='receiver_user',
        ),
    ]
