# Generated by Django 4.1.5 on 2023-04-03 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0012_rename_reciver_user_messagemodel_receiver_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='thread',
            field=models.ForeignKey(blank=True, null='True', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='social.threadmodel'),
            preserve_default='True',
        ),
    ]
